version: '3.3'

services:
  web:
    build: .
    container_name: flask_app  # Consider renaming if using FastAPI
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # App running on port 80
    expose:
      - "8000"
    environment:
      - FLASK_ENV=development  # Remove if not using Flask
      - DATABASE_URL=sqlite:///./test.db

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    # depends_on:
    #   - redis

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"


  # celery:
  #   build: .
  #   container_name: celery_worker
  #   command: celery -A app.tasks.celery_app worker --loglevel=info
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - redis

  # celery-beat:
  #   build: .
  #   container_name: celery_beat
  #   command: celery -A app.tasks.celery_app beat --loglevel=info
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - redis